### ISSUE TITLE
Never return -1 for BlockType anymore

### ISSUE THREAD

**Issue by GiantCrocodile** [vexyl/MCHawk#57]
The BlockType was designed to be of value `-1` in case of error like when a client is requesting a block outside of the map's scope/dimension. This has other negative side effects and was never used as error handling at all. Thus the value `-1` should never be returned anymore now and all BlockTypes should be `uint8_t` everywhere.

**Comment by vexyl** [comment]
Resolved with commit https://github.com/vexyl/MCHawk/commit/a20e06ea27db0c4f5e301eac8c2fd20f91a8aa36.
