### ISSUE TITLE
Add exception handling instead of returning boolean values for errors

### ISSUE THREAD

**Issue by GiantCrocodile** [vexyl/MCHawk#60]
Several cases in different classes and functions exist where a boolean value (true/false) is returned to indicate that an error happened, although it is not clear which error happened or why. We can tell a developer that his function call did fail (was `false`) but we can't differentiate between different error reasons in a function nor can we provide a meaningful error message.

This is the reason for why we should use proper error handling with exceptions.

**Comment by vexyl** [comment]
Resolved with commit https://github.com/vexyl/MCHawk/commit/4e76d0bb6b3ff8435b580549fa41c0f15c41ce1b. This isn't a perfect solution, however, but it will work for now. There really should be a custom exception class that gets thrown. There should also be some kind of association between a Lua exception and a client error message (e.g., LuaExceptionInvalidCommand->"&cInvalid command: &f" + commandName")

**Comment by vexyl** [comment]
It might be a good idea to open another issue for the above suggestion.
